### ISSUE TITLE
Gherkin Auto-Complete Breaks in ST3

### ISSUE THREAD

**Issue by RobotGetsBored** [drewda/cucumber-sublime-bundle#18]
Today I must have gotten an auto update on this package and my autocomplete stopped working. After awhile I realized that it did work, but only on new, unsaved files. As soon as I saved the file, watching the console, I would see this:

    Traceback (most recent call last):  
      File "/opt/sublime_text/sublime_plugin.py", line 358, in on_query_completions
        res = callback.on_query_completions(v, prefix, locations)
      File "GherkinAutoComplete in /home/dalvarez/.config/sublime-text-3/Installed Packages/Cucumber.sublime-package", line 103, in on_query_completions
      File "GherkinAutoComplete in /home/dalvarez/.config/sublime-text-3/Installed Packages/Cucumber.sublime-package", line 69, in is_feature_file
    TypeError: argument of type 'NoneType' is not iterable

When I uninstalled this package, everything went back to normal.

**Comment by bubenkoff** [comment]
i'll look, thanks for report

**Comment by twolfson** [comment]
This has also broken tab completion on ST2. There are no errors popping up which is frustrating but thankfully I found this via:

http://www.reddit.com/r/SublimeText/comments/2tywbd/sublime_text_3_auto_complete_stopped_working/

**Comment by bubenkoff** [comment]
i pushed some fixes, please check

**Comment by RobotGetsBored** [comment]
Do you know when it will be available through Package Control? According to the Package Control [page for this package](https://packagecontrol.io/packages/Cucumber) the latest version is from the 27th.

**Comment by RobotGetsBored** [comment]
Nope, still seems to mess up the auto complete. No initial errors in the Console. When I open up a new file and start typing, then I get an error (rough glance, looks the same as before).

    Traceback (most recent call last):
      File "/opt/sublime_text/sublime_plugin.py", line 358, in on_query_completions
        res = callback.on_query_completions(v, prefix, locations)
      File "GherkinAutoComplete in /home/dalvarez/.config/sublime-text-3/Installed Packages/Cucumber.sublime-package", line 118, in on_query_completions
      File "GherkinAutoComplete in /home/dalvarez/.config/sublime-text-3/Installed Packages/Cucumber.sublime-package", line 71, in is_feature_file
    TypeError: argument of type 'NoneType' is not iterable

**Comment by bubenkoff** [comment]
please update again

**Comment by RobotGetsBored** [comment]
I no longer get that error, but still auto completion doesn't work. Sorry for all the trouble, but I do appreciate you attempting to fix this!

**Comment by bubenkoff** [comment]
what's in console when you save the file?

**Comment by twolfson** [comment]
Nothing is in the console. It looks like your `return` for the `if` is on the wrong line.

![selection_019](https://cloud.githubusercontent.com/assets/902488/5962445/9cb6050c-a7a9-11e4-803b-6aed5abbbd9e.png)

Indenting the `return` into the `if` fixes the issue. I will submit a PR.

**Comment by bubenkoff** [comment]
that's cool you've found that it will work returning None, i wasn't sure about this looking at sublime text api docs - thanks!

**Comment by RobotGetsBored** [comment]
Yup, that did it. Thanks!

**Comment by bubenkoff** [comment]
thank You!
